# -*- coding: utf-8 -*-
"""Assignment-1_Topsis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z_E3qBKYIiODRCZ6YQiWXV4kT_HOO3cR
"""

import pandas as pd
import numpy as np

def topsis(input_file, weights_str, impacts_str, output_file):
    # Read input CSV
    df = pd.read_csv("/content/input_topsis.csv")

    # Convert criteria columns to float
    df.iloc[:, 1:] = df.iloc[:, 1:].astype(float)

    # Parse weights and impacts
    weights = np.array(list(map(float, weights_str.split(","))))
    impacts = impacts_str.split(",")

    # Validation checks
    if len(weights) != df.shape[1] - 1:
        raise ValueError("Number of weights must match number of criteria")

    if len(impacts) != df.shape[1] - 1:
        raise ValueError("Number of impacts must match number of criteria")

    if not all(i in ['+', '-'] for i in impacts):
        raise ValueError("Impacts must be '+' or '-' only")

    # Normalize weights
    weights = weights / weights.sum()

    # Extract decision matrix
    matrix = df.iloc[:, 1:].values

    # Step 1: Normalize the matrix
    norm = np.sqrt((matrix ** 2).sum(axis=0))
    normalized = matrix / norm

    # Step 2: Apply weights
    weighted = normalized * weights

    # Step 3: Ideal best and worst
    ideal_best = []
    ideal_worst = []

    for i in range(len(impacts)):
        if impacts[i] == '+':
            ideal_best.append(weighted[:, i].max())
            ideal_worst.append(weighted[:, i].min())
        else:
            ideal_best.append(weighted[:, i].min())
            ideal_worst.append(weighted[:, i].max())

    ideal_best = np.array(ideal_best)
    ideal_worst = np.array(ideal_worst)

    # Step 4: Distance calculation
    d_pos = np.sqrt(((weighted - ideal_best) ** 2).sum(axis=1))
    d_neg = np.sqrt(((weighted - ideal_worst) ** 2).sum(axis=1))

    # Step 5: TOPSIS score
    score = d_neg / (d_pos + d_neg)

    # Add results
    df["Topsis Score"] = np.round(score, 4)
    df["Rank"] = df["Topsis Score"].rank(ascending=False, method="dense").astype(int)

    # Save output
    df.to_csv(output_file, index=False)

    print("TOPSIS calculation completed successfully.")
    print(f"Output saved to {output_file}")


# -------------------- FUNCTION CALL --------------------

topsis(
    input_file="input_topsis.csv",
    weights_str="1,1,1,1,1",
    impacts_str="+,+,+,-,+",
    output_file="output.csv"
)